export const lightPurple = '#6D4DB2';
export const midPurple = '#5948EC';
export const textColor = '#FFFFFF';
export const darkPurple = '#101353';
export const pink = '#E6BAE9';
export const limeGreen = '#a2f85f ';
export const greenWhite = '#eff1ec';
export const coolWhite = '#e5e7ec';
export const black = '#0D0D0D'